#!/usr/bin/env python

from __future__ import print_function
from subprocess import call, check_output


def parse_args():
    """Handle command line arguments.
    """
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
            'id', type=str, nargs='+',
            help='the configuration file')
    args = parser.parse_args()

    return args

def main():
    args = parse_args()

    if len(args.id) == 2:
        # get all job ids
        job_str = check_output(['bjobs', '-w']).split('\n')[1:-1]
        ids = [int(string.split(' ')[0]) for string in job_str]
        # kill all in range
        ids_to_kill = [id for id in ids if (id >= int(args.id[0])) * (id <= int(args.id[1]))]
        for id in ids_to_kill:
            call(['bkill', '{0}'.format(id)])
    else:
        for id in args.id:
            call(['bkill', id])

if __name__ == '__main__':
    main()
