#!/usr/bin/python3
"""
Shell Script to ls
"""

import sys
import os

args = sys.argv[1:]
for arg in args:
    if 'festivus' in arg:
        gsarg = arg.replace('/festivus/', 'gs://')
    else:
        directory = os.getcwd()
        if 'festivus' not in directory:
            raise TypeError('Trying to gsutil ls at {0}/{1}?'.format(directory, arg))
        if arg == '.':
            arg = ''
        gsarg = '{0}/{1}'.format(directory.replace('/festivus/', 'gs://'), arg)

    # print('{0} -> {1}'.format(arg, gsarg))
    cmd = 'gsutil ls {0}'.format(gsarg)
    # print(cmd)
    os.system(cmd)
