#!/usr/bin/env python

import glob
import click
import os
import sys

def parse_args():
    """Handle the command line arguments.

    Returns the args as an argparse.Namespace object.
    """
    import argparse

    parser = argparse.ArgumentParser(description='Remove duplicates')
    parser.add_argument(
            'directory', type=str,
            help='directory we deep search for duplicates')

    args = parser.parse_args()

    return args

def main():
    args = parse_args()
    directory = args.directory
    numbers = range(1, 10)
    for number in numbers:
        # search for files
        print('Searching through {0} for duplicates with " {1}.m4a"'.format(directory, number))
        files = glob.glob('{0}/**/* {1}.m4a'.format(directory, number), recursive=True)
        if len(files) == 0:
            continue
        # confirm these files
        print('Confirming for {0} files that it is a duplicate'.format(len(files)))
        files = [f for f in files if os.path.exists(f.replace(' {0}.m4a'.format(number), '.m4a'))]

        # print files
        print('Deleting the following {0} files:'.format(len(files)))
        for f in files:
            print(f)

        # confirm if we are deleting them
        if click.confirm('Do you want to delete the above files?', default=False):
            # delete them
            for f in files:
                os.remove(f)

if __name__ == '__main__':
    main()
